name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: kennylouie/setup-ops@v0.1.0
    - name: tests
      run: |
        echo "Running tests..."
        make test
        echo "Done!"
