name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: setup-ops
      run: |
        npm install -g @cto.ai/ops
        ops account:signin -u ${{ secrets.OPS_USER_NAME }} -p ${{ secrets.OPS_USER_PW }}
    - name: tests
      run: |
        make test
        ops run @kl/maketests:0.1.1

